name: Windows Installer

on:
  workflow_dispatch:

jobs:
  build:
    name: Build installer
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust nightly + Android target
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: aarch64-linux-android

    - name: Cache Rust build
      uses: Swatinem/rust-cache@v2

    - name: Install Inno Setup via Chocolatey
      run: choco install innosetup --yes --no-progress

    - name: Download Dokan Installer
      run: curl -L --retry 10 --retry-all-errors -o ./installer/Dokan_x64.msi https://github.com/dokan-dev/dokany/releases/download/v1.5.1.1000/Dokan_x64.msi

    - name: Install cargo-ndk
      run: cargo install cargo-ndk

    - name: Compile AndroidFS
      run: ./build.ps1

    - name: Compile Installer
      run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /f installer/installer.iss'

    - name: Upload standalone
      uses: actions/upload-artifact@v4
      with:
        name: standalone
        path: ./target/release/*.exe

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: ./installer/*.exe
